spring.application.name=wms
server.port=8081
spring.datasource.url=jdbc:postgresql://db:5432/warehouse_db
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update
